import { fetchPosts } from '@/api-client'
import { IPost } from '@/models'
import {
  dehydrate,
  DehydratedState,
  QueryClient,
  useQuery,
  UseQueryResult,
} from '@tanstack/react-query'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

interface HomeProps {
  posts?: IPost[]
}

const Home: NextPage = () => {
  const x = 1

  const router = useRouter()

  const { data }: UseQueryResult<IPost[], Error> = useQuery<IPost[], Error>(
    ['posts'],
    fetchPosts,
  )
  const { data: otherData }: UseQueryResult<IPost[], Error> = useQuery<
    IPost[],
    Error
  >(['posts'], fetchPosts)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={() => router.push('/about')}>Go to about</button>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (): Promise<{
  props: { dehydratedState: DehydratedState }
}> => {
  const queryClient = new QueryClient()
  if (!queryClient.getQueryData(['posts'])) {
    await queryClient.prefetchQuery<IPost[]>(['posts'], fetchPosts)
  }

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

export default Home
